[changelog]
header = """
== Changelog ==
"""
body = """
{% if version %}
{{ timestamp | date(format="%Y-%m-%d") | default(value="") }} - version {{ version | trim_start_matches(pat="v") }}
{% for commit in commits %}* {{ commit.message | split(pat="
") | first | trim }}
{% endfor %}{% endif %}
"""

[git]
conventional_commits = false
filter_unconventional = false
sort_commits = "newest"

[[git.commit_parsers]]
message = "^Release"
skip = true

[remote.github]
owner = "AlecRust"
repo = "brevwoo"
